=== ncsa/oa4mp/server-api/src/main/resources/service.dtd
<!ELEMENT config (service)*>
<!ELEMENT service (myproxy|mysql|postgresql|fileStore|memoryStore|mail|messages)*>
<!ATTLIST service
          address CDATA #REQUIRED
          name CDATA #IMPLIED
          version CDATA #IMPLIED
          debug CDATA #IMPLIED>
<!ELEMENT messages (retryMessage)*>
<!ELEMENT retryMessage  (#PCDATA)>
<!ELEMENT keystore (#PCDATA)>
<!ATTLIST keystore
          path CDATA #REQUIRED
          password CDATA #REQUIRED
          type CDATA #IMPLIED
          factory CDATA #IMPLIED>
<!ELEMENT loa (#PCDATA)>
<!ATTLIST loa
          name CDATA #REQUIRED
          port CDATA #REQUIRED>
<!ELEMENT myproxy (keystore|loa)*>
<!ATTLIST myproxy
          host CDATA #REQUIRED
          port CDATA #REQUIRED>
<!ELEMENT clients (#PCDATA)>
<!ELEMENT clientApprovals (#PCDATA)>
<!ELEMENT transactions (#PCDATA)>
<!ELEMENT memoryStore (clients|clientApprovals|transactions)*>
<!ELEMENT fileStore (clients|clientApprovals|transactions)*>
<!ATTLIST fileStore
          dataPath CDATA #IMPLIED
          indexPath CDATA #IMPLIED
          path CDATA #IMPLIED>
<!ELEMENT mysql (clients|clientApprovals|transactions)*>
<!ATTLIST mysql
          password CDATA #REQUIRED
          port CDATA #IMPLIED
          username CDATA #REQUIRED
          schema CDATA #IMPLIED
          database CDATA #IMPLIED
          tablename CDATA #IMPLIED
          tablePrefix CDATA #IMPLIED
          driver CDATA #IMPLIED>
<!ELEMENT postgresql (clients|clientApprovals|transactions)*>
<!ATTLIST postgresql
          username CDATA #REQUIRED
          password CDATA #REQUIRED
          port CDATA #IMPLIED
          schema CDATA #IMPLIED
          database CDATA #IMPLIED
          tablename CDATA #IMPLIED
          tablePrefix CDATA #IMPLIED
          driver CDATA #IMPLIED>
<!ELEMENT messageTemplate (#PCDATA)>
<!ELEMENT subjectTemplate (#PCDATA)>
<!ELEMENT mail (messageTemplate|subjectTemplate)*>
<!ATTLIST mail
          enabled CDATA #IMPLIED
          useSSL CDATA #IMPLIED
          username CDATA #IMPLIED
          password CDATA #IMPLIED
          debug CDATA #IMPLIED
          server CDATA #IMPLIED
          port CDATA #IMPLIED
          recipents CDATA #IMPLIED>

=== ncsa/oa4mp/server-api/src/main/resources/service.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "service.dtd">
<!--
You should probably use the online dtd rather than the one supplied here with the following DOCTYPE directive:

<!DOCTYPE config PUBLIC "-//OA4MP//DTD version 1.2.2//EN" "http://cilogon.svn.sourceforge.net/viewvc/cilogon/m2-repo/dtd/1.2.2/service.dtd">

If you cannot access this for whatever reason, then certainly refer to the dtd locally or just omit it all together.
-->

<config>
 <service name="sample"
          version="1.0"
          address="https://localhost:8443/oauth">
     <myproxy host="myproxy.teragrid.org" port="7514"/>
     <mysql username="portal" password="bar">
         <transactions/>
     </mysql>
     <mysql username="client" password="bar">
         <clients/>
     </mysql>
     <mysql username="approver" password="bar">
         <clientApprovals/>
     </mysql>

     <mail enabled="true"
	   useSSL="true"
	   username="you@wherever.edu"
	   password="bar"
       debug="false"
 	   server="smtp.wherever.edu"
	   recipents="you@wherever.edu,your-alter-ego@wherever.edu">
         <messageTemplate>/path/to/xsede-message.template</messageTemplate>
         <subjectTemplate>/path/to/config/xsede-subject.template</subjectTemplate>
     </mail>
 </service>
</config>

=== ncsa/oa4mp/server-api/src/main/resources/server-test.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE config SYSTEM "service.dtd">
<!-- User in unit tests -->
<config>
    <service name="postgresql config"
             version="1.0"
             address="https://research.bigstate.edu/oauth">
        <myproxy host="myproxy.bigstate.edu"
                 port="7512"/>
        <postgresql username="foo" password="bar" schema="oauth">
            <transactions/>
            <clients/>
            <clientApprovals/>
        </postgresql>

        <fileStore path="/tmp/oa4mp">
            <transactions/>
        </fileStore>

        <memoryStore>
            <clientApprovals/>
        </memoryStore>

    </service>

    <service name="mysql config"
             version="1.0"
             address="https://research.bigstate.edu/oauth">
        <myproxy host="myproxy.bigstate.edu"
                 port="7512"/>
        <mysql username="foo" password="bar" schema="oauth">
            <transactions/>
            <clients/>
            <clientApprovals/>
        </mysql>
    </service>

    <service name="file config"
             version="1.0"
             address="https://research.bigstate.edu/oauth">
        <myproxy host="myproxy.bigstate.edu"
                 port="7512"/>
        <fileStore path="/tmp">
            <transactions/>
            <clients/>
            <clientApprovals/>
        </fileStore>
    </service>

    <service name="minimum config"
             address="https://research.bigstate.edu/oauth"/>
    <service name="mixed config"
             version="1.0"
             address="https://research.bigstate.edu/oauth">
        <fileStore path="/tmp">
            <transactions/>
        </fileStore>
        <mysql username="foo" password="bar" schema="oauth">
            <clients/>
        </mysql>
        <postgresql username="foo" password="bar" schema="oauth">
            <clientApprovals/>
        </postgresql>
        <mail enabled="true"
              useSSL="true"
              username="qqq"
              password="www"
              server="fnord.foo.baz"
              port="3321"
              recipents="tom;dick;harry">
            <messageTemplate>/var/www/config/message.txt</messageTemplate>
            <subjectTemplate>/var/www/config/subject.txt</subjectTemplate>
        </mail>
    </service>


</config>
